### PR TITLE
Fix compatibility with Node 15

### LINKED ISSUE #95: Compatibility with Node 15
In Node 15 brfs throw error `The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`, because in `readFile` or `readFileSync` is `undefined` passed.

Full error:
```
node:internal/fs/utils:634
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (node:fs:462:10)
    at ReadStream._construct (node:internal/fs/streams:61:17)
    at constructNT (node:internal/streams/destroy:288:25)
    at processTicksAndRejections (node:internal/process/task_queues:79:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### PR DESCRIPTION
**Pull request by liborm85**
Fixes #95

Allowed failures for node.js 4 and older, because is not testable on travis.

### CODE REVIEW

**Comment by drtyh2o** [comment]
Is there any plan to get this released?

**Comment by mdurling** [comment]
I just tested this fix and it resolves my issue with `node v15` ... any chance we can get this merged/published?

**Comment by liborm85** [comment]
@goto-bus-stop Can you look on it?

**Comment by mathisonian** [comment]
This is also an issue for my project (https://github.com/idyll-lang/idyll/issues/723) - hoping we can get it merged

**Comment by mathisonian** [comment]
If you need to include this functionality in your project, I released a patched version on npm: `npm i --save brfs-node-15`

**Comment by liborm85** [comment]
Node.js 16 - no error is returned

**Pull request closed without merging**
